# Generated by Django 5.2.8 on 2025-11-24 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_exposure_usd",
                    models.DecimalField(decimal_places=18, default=0, max_digits=36),
                ),
                ("total_pnl", models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                (
                    "max_drawdown_percent",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "current_drawdown_percent",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("open_positions_count", models.IntegerField(default=0)),
                ("win_rate", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                (
                    "sharpe_ratio",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("measured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "risk_metrics",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("strategy_type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(default=dict)),
                (
                    "min_confidence",
                    models.DecimalField(decimal_places=4, default=0.7, max_digits=5),
                ),
                (
                    "max_position_size",
                    models.DecimalField(decimal_places=18, default=1000, max_digits=36),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "strategies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("buy", "BUY"), ("sell", "SELL"), ("hold", "HOLD")], max_length=10
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "suggested_price",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                (
                    "suggested_amount",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("is_executed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="decision_engine.strategy",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="trading.token",
                    ),
                ),
            ],
            options={
                "db_table": "trading_signals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[("buy", "BUY"), ("sell", "SELL"), ("hold", "HOLD")], max_length=10
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approval_confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("risk_score", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("position_size", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "target_price",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                (
                    "stop_loss",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                (
                    "take_profit",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="trading.order",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="trading.token",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="decision_engine.tradingsignal",
                    ),
                ),
            ],
            options={
                "db_table": "decisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(
                fields=["strategy", "-created_at"], name="trading_sig_strateg_d97bb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(
                fields=["token", "signal_type"], name="trading_sig_token_i_302541_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(fields=["is_executed"], name="trading_sig_is_exec_a3d575_idx"),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["approved", "-created_at"], name="decisions_approve_93b767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(fields=["token"], name="decisions_token_i_f8152b_idx"),
        ),
    ]
