# Generated by Django 5.2.8 on 2025-11-24 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("followers_count", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=1)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracked_accounts",
                "ordering": ["-priority", "-followers_count"],
            },
        ),
        migrations.CreateModel(
            name="AccountMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("followers_count", models.IntegerField()),
                ("following_count", models.IntegerField()),
                ("tweet_count", models.IntegerField()),
                ("listed_count", models.IntegerField(default=0)),
                (
                    "engagement_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("measured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="x_tracker.trackedaccount",
                    ),
                ),
            ],
            options={
                "db_table": "account_metrics",
                "ordering": ["-measured_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "-measured_at"], name="account_met_account_f063fc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tweet_id", models.CharField(max_length=100, unique=True)),
                ("text", models.TextField()),
                ("created_at_twitter", models.DateTimeField()),
                ("retweet_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("reply_count", models.IntegerField(default=0)),
                ("quote_count", models.IntegerField(default=0)),
                ("is_retweet", models.BooleanField(default=False)),
                ("retweeted_tweet_id", models.CharField(blank=True, max_length=100, null=True)),
                ("has_media", models.BooleanField(default=False)),
                ("has_url", models.BooleanField(default=False)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to="x_tracker.trackedaccount",
                    ),
                ),
            ],
            options={
                "db_table": "tweets",
                "ordering": ["-created_at_twitter"],
                "indexes": [
                    models.Index(
                        fields=["account", "-created_at_twitter"], name="tweets_account_321d94_idx"
                    ),
                    models.Index(fields=["tweet_id"], name="tweets_tweet_i_7cc906_idx"),
                    models.Index(fields=["-created_at_twitter"], name="tweets_created_c5176e_idx"),
                ],
            },
        ),
    ]
