# Generated by Django 5.2.8 on 2025-11-24 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("x_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("centroid_embeddings", models.JSONField(blank=True, null=True)),
                ("avg_sentiment", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("tweet_count", models.IntegerField(default=0)),
                ("dominant_tickers", models.JSONField(default=list)),
                ("strength_score", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "signal_clusters",
                "ordering": ["-strength_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic", models.CharField(max_length=200, unique=True)),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                ("mention_count", models.IntegerField(default=0)),
                ("sentiment_score", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("velocity", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("peak_at", models.DateTimeField(blank=True, null=True)),
                ("is_trending", models.BooleanField(default=True)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "trending_topics",
                "ordering": ["-velocity", "-mention_count"],
                "indexes": [
                    models.Index(
                        fields=["is_trending", "-velocity"], name="trending_to_is_tren_5d2e56_idx"
                    ),
                    models.Index(fields=["ticker"], name="trending_to_ticker_1c1c4d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TweetFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sentiment_score",
                    models.CharField(
                        choices=[
                            ("very_negative", "VERY_NEGATIVE"),
                            ("negative", "NEGATIVE"),
                            ("neutral", "NEUTRAL"),
                            ("positive", "POSITIVE"),
                            ("very_positive", "VERY_POSITIVE"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("contains_ticker", models.BooleanField(default=False)),
                ("mentioned_tickers", models.JSONField(default=list)),
                ("contains_price_prediction", models.BooleanField(default=False)),
                ("urgency_score", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                (
                    "influence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("embeddings", models.JSONField(blank=True, null=True)),
                ("keywords", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tweet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="x_tracker.tweet",
                    ),
                ),
            ],
            options={
                "db_table": "tweet_features",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TweetClusterMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="x_signals.signalcluster",
                    ),
                ),
                (
                    "tweet_features",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="x_signals.tweetfeatures",
                    ),
                ),
            ],
            options={
                "db_table": "tweet_cluster_memberships",
                "ordering": ["-similarity_score"],
            },
        ),
        migrations.AddIndex(
            model_name="tweetfeatures",
            index=models.Index(fields=["sentiment_score"], name="tweet_featu_sentime_84304b_idx"),
        ),
        migrations.AddIndex(
            model_name="tweetfeatures",
            index=models.Index(fields=["contains_ticker"], name="tweet_featu_contain_ef0fc0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tweetclustermembership",
            unique_together={("tweet_features", "cluster")},
        ),
    ]
