# Generated by Django 5.2.8 on 2025-11-24 02:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.CharField(max_length=42, unique=True)),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("decimals", models.IntegerField(default=18)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tokens",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=42, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                ("entry_price", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "current_price",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                (
                    "pnl",
                    models.DecimalField(decimal_places=18, default=Decimal("0"), max_digits=36),
                ),
                (
                    "pnl_percent",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=10),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading.token",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "positions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(choices=[("buy", "BUY"), ("sell", "SELL")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("submitted", "SUBMITTED"),
                            ("filled", "FILLED"),
                            ("partially_filled", "PARTIALLY_FILLED"),
                            ("cancelled", "CANCELLED"),
                            ("failed", "FAILED"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                ("expected_price", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "executed_price",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
                ),
                (
                    "slippage_percent",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("gas_used", models.BigIntegerField(blank=True, null=True)),
                ("transaction_hash", models.CharField(blank=True, max_length=66, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.position",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.token",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=66, unique=True)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("from_address", models.CharField(max_length=42)),
                ("to_address", models.CharField(max_length=42)),
                ("value", models.DecimalField(decimal_places=18, max_digits=36)),
                ("gas_used", models.BigIntegerField(blank=True, null=True)),
                ("gas_price", models.BigIntegerField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_logs",
                        to="trading.order",
                    ),
                ),
            ],
            options={
                "db_table": "transaction_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_hash"], name="transaction_transac_06d2c3_idx"
                    ),
                    models.Index(fields=["from_address"], name="transaction_from_ad_06caf6_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["wallet", "is_open"], name="positions_wallet__90c3ae_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["token", "is_open"], name="positions_token_i_45dedc_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["wallet", "status"], name="orders_wallet__b1bd1a_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["transaction_hash"], name="orders_transac_c7e2d7_idx"),
        ),
    ]
