# Generated by Django 5.2.9 on 2025-12-03 00:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("balance", models.DecimalField(decimal_places=0, max_digits=78)),
                ("first_acquired", models.DateTimeField()),
                ("has_initiated_transfer", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "token_holders",
                "ordering": ["-balance"],
            },
        ),
        migrations.CreateModel(
            name="TokenHolderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("balance", models.DecimalField(decimal_places=0, max_digits=78)),
                ("has_initiated_transfer", models.BooleanField(default=False)),
                ("snapshot_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "token_holder_snapshots",
                "ordering": ["-snapshot_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenHolderSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("next_offset", models.CharField(blank=True, max_length=255, null=True)),
                ("total_holders", models.IntegerField(default=0)),
                ("sync_in_progress", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "token_holder_syncs",
            },
        ),
        migrations.AddField(
            model_name="token",
            name="chain_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="token",
            name="address",
            field=models.CharField(max_length=42),
        ),
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("address", "chain_id")},
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["chain_id"], name="tokens_chain_i_25d009_idx"),
        ),
        migrations.AddField(
            model_name="tokenholder",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holders",
                to="trading.token",
            ),
        ),
        migrations.AddField(
            model_name="tokenholdersnapshot",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holder_snapshots",
                to="trading.token",
            ),
        ),
        migrations.AddField(
            model_name="tokenholdersync",
            name="token",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holder_sync",
                to="trading.token",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenholder",
            index=models.Index(fields=["token", "-balance"], name="token_holde_token_i_dfeecf_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenholder",
            index=models.Index(fields=["wallet_address"], name="token_holde_wallet__e2f8b2_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenholder",
            index=models.Index(fields=["first_acquired"], name="token_holde_first_a_21185b_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenholder",
            index=models.Index(
                fields=["has_initiated_transfer"], name="token_holde_has_ini_3d2c15_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tokenholder",
            unique_together={("token", "wallet_address")},
        ),
        migrations.AddIndex(
            model_name="tokenholdersnapshot",
            index=models.Index(
                fields=["token", "wallet_address", "-snapshot_at"],
                name="token_holde_token_i_fa7a79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenholdersnapshot",
            index=models.Index(
                fields=["token", "-snapshot_at"], name="token_holde_token_i_3efca9_idx"
            ),
        ),
    ]
